services:
  - type: web
    name: hozwork-backend
    env: docker
    plan: free
    region: frankfurt
    rootDir: backend
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
